several aspects brought from remind to remindStart
johanneskoch94/remindStart pull request #1
Opened 2022-03-30 14:04 UTC by orichters

- enable chooseSlurmConfig to be called with identifier
- allow slurmConfig to be supplied in scen_conf
- generalize chooseFolder to chooseFromList
- add --test flag where runs are not actually submitted (may still be improved)
- add --debug flag where runs are started in debug mode
- add --interactive flag where user can select the runs to be started from scenario_config file

I did not really have time to test all that, but wanted first that you have a look at it, I'm still not completely understanding the structure of the package.

2022-03-30 14:46 UTC, johanneskoch94 requested changes
Amazing! Thanks for all the extra functionality :) I left some comments. What I think we still have to address is the call to choosSlurmConfig here: https://github.com/johanneskoch94/remindStart/blob/e9826577e0b6f7240c099d6ab5fd44d36334229d/R/submitScenariosToSlurm.R#L7 . I'm no quite sure if you left it on purpose, or if it's even still necessary? Maybe we can talk about that.

2022-03-30 14:46 UTC, johanneskoch94 commented on R/start.R
> +    scenarios <- read_scenario_cfg(configFile, debug, interactive, testOneRegi)
Looks like you're passing debug and testOneRegi unnecessarily here.. At least the function definition hasn't been adapted. This should actually through an error normally, since you're passing to many arguments. Has no error been thrown?

2022-03-30 14:46 UTC, johanneskoch94 commented on R/chooseSlurmConfig.R
> +  if (! length(identifier) == 1 || ! identifier %in% paste(seq(1:16))) {
I would suggest simply using `!=` rather than `! ... == ...`

2022-03-30 14:46 UTC, johanneskoch94 commented on R/chooseSlurmConfig.R
> +  if (! exists("wasselected")) {
When using the `exists()` function within a package, I think it's better to set `inherits = FALSE`. This should prevent the function of looking all the way up in the global environment for such an object, which a user may have set. (Best check if that works off the bat though, cause I'm not super confident I understand which environments are searched by default, if `inherits = FALSE`.. if not, you may have to specify the environment in which `exists()` should check - in this case, that is simply the function environment of chooseSlurmConfig.)

2022-03-30 14:46 UTC, johanneskoch94 commented on R/configureCfg.R
> +    if (cfg$slurmConfig %in% paste(seq(1:16))) cfg$slurmConfig <- choose_slurmConfig(identifier = cfg$slurmConfig)
Is this a typo? Do you mean `chooseSlurmConfig()`?

2022-03-30 15:14 UTC, orichters commented
> Amazing! Thanks for all the extra functionality :) I left some comments. What I think we still have to address is the call to choosSlurmConfig here:
> 
> https://github.com/johanneskoch94/remindStart/blob/e9826577e0b6f7240c099d6ab5fd44d36334229d/R/submitScenariosToSlurm.R#L7
> . I'm no quite sure if you left it on purpose, or if it's even still necessary? Maybe we can talk about that.

The alternative would be to first check whether any of the runs the will be started has not a valid slurmConfig in the scenario_config file. Currently, it asks the user to specify it, although it may be that it will actually never be used.

2022-03-30 15:17 UTC, johanneskoch94 reviewed
Looks good.

2022-03-30 15:30 UTC, johanneskoch94 commented
Ok, so currently the user specifies a slurmConfig for all runs, but that then gets overwritten -job specifically- by whatever is in the config file, right? We can leave it like that for now :)

2022-03-30 15:31 UTC, johanneskoch94 approved these changes

2022-03-30 15:34 UTC, orichters commented
> Ok, so currently the user specifies a slurmConfig for all runs, but that then gets overwritten -job specifically- by whatever is in the config file, right? We can leave it like that for now :)

Exactly. And if --testOneRegi is selected, it always starts with what the user selected, overwriting the scenario config file. We might implement that for debug as well.

2022-03-30 15:36 UTC, orichters commented
There is still one issue that doesn't work like I hoped. The --restart combined with --testOneRegi or --debug should overwrite the settings, but this requires moving the full.gms out of the way
```
system(paste0("mv output/", outputdir, "/full.gms output/", outputdir, "/full_old.gms"))
```

2022-03-30 15:47 UTC, johanneskoch94 commented
Ah, those options (in restart mode) would mean editing the full.gms file, is that it? And you don't want to do that because it would make it impossible to restart the run normally afterwards, I assume? So you would like to create a copy of the original, full.gms, name it full_old.gms (and then switch it back at the end?), but how is the new full.gms created?

2022-03-30 15:50 UTC, orichters commented
Yes. Once you move away the full.gms to full_old.gms (and possibly fulldata.gdx to fulldata_old.gdx), scripts/start/prepare_and_run.R recreates it.

2022-03-30 15:55 UTC, johanneskoch94 commented
I think I know where the issues stem from. In remindStart, prepare_and_run.R is split into "prepare" and "run". Currently, if restart is activated, prepare isn't run at all. So that would have to be changed. (That also reminds me - your functionality in remind, of being able to restart an entire cascade, won't work here either at the moment.. ). I will take a look at this.

2022-03-30 16:13 UTC, orichters commented
Well, this problem is also present in remind. I haven't fully understood how it is supposed to work in remindStart.

2025-03-26 08:42 UTC, orichters commented
@johanneskoch94: seems like there is no need for it anymore? So I close here.

2025-03-26 08:42 UTC, closed without merging